apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: abhiacrxqxrr9.azurecr.io/myapp:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: acr-secret  # Optional: if using secrets
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 3000
